### PR TITLE
Update README with links to other useful resources

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
@antoninbas Pinging you on this possible README update for this project, too.  I got the links from a discussion a while back on the p4-lang Slack channel, recommended by you and Carmelo.  Feel free to ping someone else if you think they would be more appropriate to review, and/or merge this or a similar change.

**Comment by jafingerhut** [comment]
@liujed-intel Do you know who might be willing to merge this in (or some variant of it if there are suggested changes?)

**Comment by liujed-intel** [comment]
@jafingerhut, looks like I have merge capability. The changes look fine to me. Let me know when you're ready to merge?

**Comment by jfingerh** [comment]
I did a quick double-check of the links I added to see if they still looked up to date, and updated one of them that the project said it was no longer maintained, and pointed at a newer one.

It looks ready to merge to me.

**Pull request merged**
